name: Wheels

on: [push, pull_request]

jobs:
  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
        arch: [auto]
        include:
          - os: windows-2019
            cmake_generator: "Visual Studio 16 2019"
            cmake_generator_platform: "x64"
            cibw-arch: AMD64
          - os: windows-2019
            cmake_generator: "Visual Studio 16 2019"
            cmake_generator_platform: "Win32"
            cibw-arch: x86
          - os: ubuntu-20.04
            arch: aarch64

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1

      - name: Build wheels
        env:
          CIBW_ENVIRONMENT_WINDOWS: >
            CMAKE_GENERATOR="${{ matrix.cmake_generator }}"
            CMAKE_GENERATOR_PLATFORM="${{ matrix.cmake_generator_platform }}"
          CIBW_ARCHS_WINDOWS: ${{ matrix.cibw-arch }}
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_SKIP: pp* *-musllinux_*  cp311*
          COMSPEC: C:\Program Files\PowerShell\7\pwsh.EXE
        run: |
            python -m cibuildwheel --output-dir wheelhouse python/

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  publish:
    needs: wheels
    name: Publish wheels to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: Publish wheels to PyPI

        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifact
